openapi: 3.0.0
info:
  title: RoadIQ Mock API
  version: 0.1.0
paths:
  /api/v1/shipments:
    get:
      summary: List shipments
      parameters:
        - in: query
          name: q
          schema: { type: string, example: "carrier:DHL status:IN_TRANSIT" }
      responses:
        '200':
          description: OK
  /api/v1/shipments/{id}:
    get:
      summary: Get shipment
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string, example: "SHP-74219" }
      responses:
        '200':
          description: OK
  /ws/updates:
    get:
      summary: WebSocket endpoint for live events
